[gcp_service_account]
type = "service_account"
project_id = "save-patient-schedule"
private_key_id = "5bbd55c99a8ef0c4642ab5f1849cd72301949334"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDA9YwQWgjv9PAE
9/Aw6POtEyXSKBfudy8cPo38EUD9qpvkvKZttLmG1w3d7tKfqdIQlo8vjE/vuQ2z
nVtSFzlAkXpabE6b/C+kitW8oMeXl60TjQFhCkc4RUEP4P4w0lxEs46Y7P6NTyGr
EM6u6XVlNyqC4ERVfSQxzUCJY2ycVzyjSBynp5PHLXSJ9PKLruNUJC03Sxm2Uemg
aqa9UE2brOEELjPH+wNtDIA1r4DRyI0E7vViXBaN+KMK35Z1yKShG/ZJ/7HyLzty
II5oqhwt5Zh0CXv4SDo+sH2OiotfXGqjH96eTRSuyNkdUsRNeO9rzMi3L/mwx4lf
5m+86ZUtAgMBAAECggEAFs6fJsqhjk0+9nNg3EMYlD80Y/XxuDG1q4q4SRA4BJOf
GAb1S/fFywqNvMru8cjGh8fn9jiJNT5EAJQrmFUe4wMe+WOeWgERl4sCbuh5FvGq
Vyp+PHxUxTGoWkpfeSFQHx2zD9/JSaYOBnR23YVCJzvBRlVgNlOTjOBkDaknDAZu
F0+F0fcwamJT23Etpm9NIkyVREUKFUdpTTgkyp/i8Gnt6nO8VL7tiGNe/ZOHCC1d
FVIp7Lnt/G/Vee9rPugjMe6+HaS+xmEiJPMZQ+STYluEXaEUpsxbAJZvEVhUvIWO
kaTmzPQBwkmMGEccD1aUsmbAlfil5Fu4Qx+fA6YsUQKBgQDlQUdidpWr3PUYQngF
7HwRcOTCjj9Gt9Tv/bWFFfU0salAS65TQD14JcooJEYhgTOjGUZrste/jhc+EyNY
BojZqAR6t+P0nTK0WuuP4QkOAAHFawX5//rW+pjMOVrPYq2palFvxe3Vujm5VW7c
xAq+f/Kbtdpfvoh7VqyVBvB6vQKBgQDXeEpFmQw1goG4OAUt3zTRKEUj2/z7bSaC
jvRrIsse2lZNu3Guh2KFHNhL00v9JX1/rC5XklLZ8Ox+Q/kL82vXwqeyBYA71iiW
p1Slurw4W/qeyhM4m1h5SUiCEqOOtz8wbDBqJABGVxL1Hw53umMC6RPvsX2HNSxv
uTyPS0djMQKBgESIAhXeCxnoIGBTJlvm+KOiEtBSA3pZY88mEYgqKzXIUicFOKRs
VLPA4DClv00uuUftO07glHwPtsT4pZ0fvvMJteUVaZBrGYgukbJd+/3yZJUmTBAS
xGJVYS3Ti2DpR66YOKXoDhPQ6oaLkmtuMyQFTXncn931MAlmvIqEG4klAoGBAK59
wqAEJkf7LTPTYhZY6PvswbkdgQzXwtT+Ed/lKFsO8881WgW9q8IiruMQ9TvHLY/E
Dy9p1uCZ49sJDtlnwtDS2V0oaUWL1AjU747a32xAyH/pI5G28/ocp7R2ha+gpHKB
Wt/J0dMk1rxc7yl0bpQ/zp5QvVhObnL3rpxYmTIxAoGAAefWJuTfxRSa7k6PRopj
H4LhsPmQcyK+goIoeFrzk5X12+nXrPLNh1u3md1PlCQ76tCXSbeGtJCI8NAYxuU/
oT6nogArTzUVwAyhQ1sZoyyN3qpwH1D6yucwgvOzIX6ya++KxOFlbzh5XHAOCKSL
9ucf5x93/9/Nouf6JAyXvpc=
-----END PRIVATE KEY-----"""
client_email = "scheduler-bot@save-patient-schedule.iam.gserviceaccount.com"
client_id = "113982208671546299804"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/scheduler-bot%40save-patient-schedule.iam.gserviceaccount.com"
