
[gcp_service_account]
type = "service_account"
project_id = "lunar-bonus-456012-g9"
private_key_id = "9f568bbf5c246f45538745033761cc03e7652fcb"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+Ss4vAAlwjeyi
yz8DdvmoG6t49iJX++TLrOU2h5v339EISKUC9xRYmpBtk7I70Vn/WsS6d1vrhDaB
Y7Jj0yVXwCKci1mKoaOAGw/Cv1iU2aoTic6AmhavczDOTBCI9PQjyInm6eRTyq+3
g4XAb3/6qrOUu2Y0quEh8NJAKIDhiZ5VSL8ZQpQdcj9/45BbJkT7OEKXtTpNS0Ge
8G2f8oRh9D8wSghfpve8mbkiWQzFjp2EqPjB3nNiPA1AgdbXogB9GtQdxV9Fk4xn
mSWNjhxB0VSHIZyDPV7J1zYuqI8JMDVfqm9WT+VTZLpMd9de8HHab3hALLbHlvmh
X2hDYYnDAgMBAAECggEAHnhf94qr+EfhglfFKUrdwxtbI61V5nzBMBPpSAgC43gF
QqxPL+Bcc6ucQM+LlKR7IrZoFeuS3m13RNSv9egTbK+pWyO9HMOxKIwsw+RbzMnl
v+crF9CUnVd2kzH+289NYIV1/3GoS/qClIIM4rl35q16v/AZ94j9L7AeGoPhzzsx
QZcNfDiOQZdIcC1JYBVBgs8HDvpTC6WaKEhIurYhijXcXpQX4FxKi5kMPj6dJ6Qn
Cj4P+k2BqDrxQuQARrMbUpVI8H3VzdAvLy2BHIJFP42SSNIUnnybZvVqaNQB6KQP
5lBySi3MhAdtuYHAkcMYtH/pnBZAhvnnSaBhNn5QQQKBgQDpdTN3dWj/noqoH8gB
+0AUgDxQXMfm+K3cNz1aWOLqpTyB111oW0YTLLszStk1PoWksXtOSo/DXFjTQ1rS
NyYBHZM1HLPwJZskk2aebygHPAE1PEJAbUvexjWV3NuSRojtMdfnFY93OmGwejS5
smy+U9mBKuLTJ+J7wl7mzWmTcQKBgQDQqpobsrrUsxJ6EOE26O8tNb0CuJNnxi6A
b/umWsBDIIHpDWLt3+EwF15OoQdxgHcfaHK/MVr7zMn3P59BpVRhNEmF+v/QUp1K
bJmQlWmA2jlEp+fc4H0XIHI3zk1V1a6i0jxLM6AERuAo4Kr8zSm4tRFBGOcGrHo6
8WdiBNYucwKBgQCyM1USxVtdaz45sPCxmoBCZdQkH34zbvT/GGdLlHe5VmGGVscl
Bi7KKiXGtEZyXwQSP6t4im+MVuwybsJfndrzlQitzPgIwhvXYnA9VWm/g+0EHrgP
h54XMULr3sb3s8GHFLnR2WJGRxkUZWPjry9UZJqs/vhe5534i9h24qrI8QKBgQDD
46SQ5BTooMNzvGzw83O1aYFrEIOxJCd7g6Um4oMjgVzzwBFjZo0sbIOoJRurvgIW
hiNSwa68O+BOMHf9VIwGROPQ13VXyHbI63KufNVylWq1vTq57DUChP80zINlVRiA
2gSoRGqwGSlOtrtOX/wO3ky4Y/xeE4Ub2IxJRGkdaQKBgE3CaRM47IWPdzJg3R6Y
vw3+hfKRQpQb/9jUG1cBZGR1ISszgbFT7btlJh6FjF4i93Rw8oGzCNpq0/wnCU4Y
4o3pJU0kfXudu4GHIfkGxt8tw08phwaUTTiT+1wDJdAIoq4BLoFVku2n1P4o6O+Z
HBeQ5VkLrZNcmrxbWjM5ksZi
-----END PRIVATE KEY-----"""
client_email = "streamlit-accessor@lunar-bonus-456012-g9.iam.gserviceaccount.com"
client_id = "101455944684194397990"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-accessor%40lunar-bonus-456012-g9.iam.gserviceaccount.com"
